permission: "lunatic.gerente"
slot: 4
sell-price:
  lunatic.lunatic: 6
  lunatic.mvp: 5
  lunatic.vip: 4
  default: 3
actionbar: "&b+{blocks} bloco(s) : &a+{value} coins"
pickaxe:
  name: "&ePicareta &7[{blocks}]"
  lore:
    - ""
    - "&7Eficiência: &f{efficiency}"
    - "&7Fortuna: &f{fortune}"
    - "&7Explosivo: &f{explosive}"
    - ""
menu:
  title: "&8[Mineração] Encantamentos"
  hotbars: 6
  info:
    slot: 12
    skull-url: "b62651879d870499da50e34036800ddffd52f3e4e1993c5fc0fc825d03446d8b"
    name: "&5Encantamentos"
    lore:
      - ""
      - "&7Encante abaixo aí!!"
      - ""
  enchantment_item:
    name: "&7"
    lore:
      - ""
      - "&7Encante abaixo aí!!"
      - ""
  enchantments:
    name: "&7{enchantment}"
    lore:
      - ""
      - "{description}"
      - ""
      - "&7Nível atual: &f{level}"
      - "&7Nível máximo: &f{max}"
      - "&7Preço: &f{price} blocos"
      - ""
      - "&fClique para evoluir o encantamento."
      - ""
    can_skull-url: "8e9b27fccd80921bd263c91dc511d09e9a746555e6c9cad52e8562ed0182a2f"
    cannot_skull-url: "5fde3bfce2d8cb724de8556e5ec21b7f15f584684ab785214add164be7624b"
    max_skull-url: "e79add3e5936a382a8f7fdc37fd6fa96653d5104ebcadb0d4f7e9d4a6efc454"
  pickaxe_slot: 14
  unavailable:
    name: "&cEncantamento indisponível."
    lore:
      - ""
      - "&csei lá"
      - ""
    skull-url: "e7f9c6fef2ad96b3a5465642ba954671be1c4543e2e25e56aef0a47d5f1f"
    slots:
      - 31
      - 32
      - 33
      - 34
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
enchantments:
  explosive:
    description:
      - "&7Esse encantamento irá ter uma chance de quebrar uma área de 3x3."
    name: "Explosivo"
    max: 100
    slot: 30
    price: 250
    multiplier: 2
    percent: 200
    radius: 3
  efficiency:
    description:
      - "&7Esse encantamento irá fazer a sua picareta quebrar blocos mais rápido."
    name: "Eficiência"
    max: 20
    slot: 28
    price: 38
    multiplier: 1.4
  fortune:
    description:
      - "&7Esse encantamento irá acrescentar o valor da venda de seus blocos."
    name: "Fortuna"
    max: 50
    slot: 29
    price: 67
    multiplier: 1.75
messages:
  join_set:
    - "&a&lMINAS &fVocê definiu a entrada da mina."
  leave_set:
    - "&a&lMINAS &fVocê definiu a saída da mina."
  without_permission:
    - "&cVocê não possui permissão para executar esse comando."
  join:
    - ""
    - "&a&lMINAS &fVocê entrou na mina."
    - ""
  leave:
    - ""
    - "&a&lMINAS &fVocê saiu da mina."
    - ""