name: lunatic-mines
version: 1.0
author: SrGeneX
main: br.com.lunaticmc.mines.Mines
depend:
  - lunatic-blocks
  - Vault
softdepend:
  - PlaceholderAPI
commands:
  mina:
    aliases: [mine, mines, minas, minerar, picareta, pickaxe]